apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsecrets.sec.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: sec.upbound.io/v1alpha1
    kind: XSecret
  resources:
    - name: kv-v2-secret-mount
      base:
        apiVersion: vault.vault.upbound.io/v1alpha1
        kind: Mount
        spec:
          forProvider:
            externalEntropyAccess: false
            path: "kv-v2"
            type: "kv-v2"
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-kv-v2-secret-mount"
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider
          toFieldPath: status.kvV2SecretMount
          policy:
            fromFieldPath: Required
    - name: transit-secret-mount
      base:
        apiVersion: vault.vault.upbound.io/v1alpha1
        kind: Mount
        spec:
          forProvider:
            externalEntropyAccess: false
            path: "transit"
            type: "transit"
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-transit-secret-mount"
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider
          toFieldPath: status.transitSecretMount
          policy:
            fromFieldPath: Required
    - name: transit-secret-backend-key
      base:
        apiVersion: transit.vault.upbound.io/v1alpha1
        kind: SecretBackendKey
        spec:
          forProvider:
            allowPlaintextBackup: false
            backend: "transit"
            convergentEncryption: false
            deletionAllowed: true
            derived: false
            exportable: false
            keySize: 0
            minDecryptionVersion: 1
            minEncryptionVersion: 0
            # The type of key to create.
            # Currently-supported types are:
            # - aes128-gcm96
            # - aes256-gcm96
            # - chacha20-poly1305
            # - ed25519
            # - ecdsa-p256
            # - ecdsa-p384
            # - ecdsa-p521
            # - rsa-2048
            # - rsa-3072
            # - rsa-4096
            type: "aes256-gcm96"
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-transit-secret-backend-key"
        - fromFieldPath: spec.parameters.transitKeyName
          toFieldPath: spec.forProvider.name
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider
          toFieldPath: status.transitSecretBackendKey
          policy:
            fromFieldPath: Required
