apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvaults.sec.upbound.io
spec:
  compositeTypeRef:
    apiVersion: sec.upbound.io/v1alpha1
    kind: XVault
  resources:
    - name: xVaultInstall
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XVaultInstall
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
          transforms:
            - type: string
              string:
                fmt: "%s-install"
        - type: ToCompositeFieldPath
          fromFieldPath: status.xVaultInstall
          toFieldPath: status.vaultXVaultInstall
          policy:
            fromFieldPath: Required
    - name: xVaultAuth
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XAuth
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
          transforms:
            - type: string
              string:
                fmt: "%s-auth"
        - fromFieldPath: spec.parameters.dataJsonSecretRef
          toFieldPath: spec.parameters.dataJsonSecretRef
        - fromFieldPath: spec.parameters.user
          toFieldPath: spec.parameters.user
        - fromFieldPath: status.vaultXVaultInstall.state
          toFieldPath: spec.parameters.vaultDeployedState
          policy:
            fromFieldPath: Required
    - name: xVaultSecrets
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XSecret
        spec:
          parameters:
            providerConfigName: vault-provider-config
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: spec.parameters.transitKeyName
          toFieldPath: spec.parameters.transitKeyName
        - fromFieldPath: status.vaultXVaultInstall.state
          toFieldPath: spec.parameters.vaultDeployedState
          policy:
            fromFieldPath: Required
    - name: xVaultPolicies
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XPolicy
        spec:
          parameters:
            providerConfigName: vault-provider-config
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: status.vaultXVaultInstall.state
          toFieldPath: spec.parameters.vaultDeployedState
          policy:
            fromFieldPath: Required
    - name: xVaultUser
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XVaultUser
        spec:
          parameters:
            id: configuration-vault-user
