apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvaults.sec.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: sec.upbound.io/v1alpha1
    kind: XVault
  resources:
    - name: xVaultAuth
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XAuth
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
          transforms:
            - type: string
              string:
                fmt: "%s-auth"
        - fromFieldPath: spec.parameters.dataJsonSecretRef
          toFieldPath: spec.parameters.dataJsonSecretRef
        - fromFieldPath: spec.parameters.user
          toFieldPath: spec.parameters.user
    - name: xVaultSecrets
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XSecret
        spec:
          parameters:
            providerConfigName: vault-provider-config
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
          transforms:
            - type: string
              string:
                fmt: "%s-secrets"
        - fromFieldPath: spec.parameters.transitKeyName
          toFieldPath: spec.parameters.transitKeyName
    - name: xVaultPolicies
      base:
        apiVersion: sec.upbound.io/v1alpha1
        kind: XPolicy
        spec:
          parameters:
            providerConfigName: vault-provider-config
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
          transforms:
            - type: string
              string:
                fmt: "%s-policy"
