---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvaultinstalls.sec.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: sec.upbound.io/v1alpha1
    kind: XVaultInstall
  resources:
    - name: vault-namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: vault
          providerConfigRef:
            name: kubernetes-provider-config
    - name: vault-creds
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: kubernetes-vault-creds-secret
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: vault-creds
                namespace: vault
              stringData:
                credentials: |
                  {
                    "token_name": "vault-creds-test-token",
                    "token": "root"
                  }
            type: Opaque
          providerConfigRef:
            name: kubernetes-provider-config
    - name: vault-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: vault
        spec:
          deletionPolicy: Delete
          rollbackLimit: 3
          forProvider:
            namespace: vault
            skipCreateNamespace: false
            chart:
              name: vault
              repository: https://helm.releases.hashicorp.com
              version: "0.27.0"
            values:
              server:
                dev:
                  enabled: true
                  devRootToken: root
            wait: true
          providerConfigRef:
            name: helm-provider-config
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider
          toFieldPath: status.xVaultInstall
          policy:
            fromFieldPath: Required
    - name: helm-provider-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: helm.crossplane.io/v1beta1
              kind: ProviderConfig
              metadata:
                name: helm-provider-config
              spec:
                credentials:
                  source: InjectedIdentity
          providerConfigRef:
            name: kubernetes-provider-config
    - name: vault-provider-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: vault.upbound.io/v1beta1
              kind: ProviderConfig
              metadata:
                name: vault-provider-config
              spec:
                add_address_to_env: false
                headers: {name: test, value: "e2e"}
                max_lease_ttl_seconds: 300
                max_retries: 10
                max_retries_ccc: 10
                namespace: vault
                skip_child_token: true
                skip_get_vault_version: true
                skip_tls_verify: true
                tls_server_name: ""
                vault_version_override: "1.15.2"
                credentials:
                  source: Secret
                  secretRef:
                    name: vault-creds
                    namespace: vault
                    key: credentials
          providerConfigRef:
            name: kubernetes-provider-config
      patches:
        - fromFieldPath: spec.parameters.vaultAddress
          toFieldPath: spec.forProvider.manifest.spec.address
