---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvaultinstalls.sec.upbound.io
spec:
  group: sec.upbound.io
  names:
    kind: XVaultInstall
    plural: xvaultinstalls
  claimNames:
    kind: VaultInstall
    plural: vaultinstalls
  connectionSecretKeys:
    - kubeconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: >-
                    Vault Installation configuration parameters.
                  properties:
                    id:
                      type: string
                      description: >-
                        ID of this Vault that other objects will
                        use to refer to it.
                    vaultAddress:
                      type: string
                      description: >-
                        Optional VAULT_ADDR if you bring your own.
                        Format is http(s)://<NAME>:<PORT>.
                        Example is http(s)://vault-addr.domain.net:8200.
                      default: http://vault.vault:8200
                    deletionPolicy:
                      description: >-
                        When the Composition is deleted,
                        delete the AWS resources. Defaults to Delete.
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                  required:
                    - id
              required:
                - parameters
            status:
              type: object
              properties:
                xVaultInstall:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
